<?php
$numero = $_GET["textn"];
switch ($numero) {
	case 1:
		echo '<select name="combo">';
		echo '<option value="1" selected>Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';    
		break;
	case 2:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2" selected>Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';  
		break;
	case 3:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3" selected>Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';  
		break;
	case 4:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4" selected>Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>'; 
		break;
	case 5:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5" selected>Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';
		break;
	case 6:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6" selected>Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>'; 
		break;
	case 7:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7" selected>Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';
		break;
	case 8:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8" selected>Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';
		break;
	case 9:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9" selected>Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';
		break;
	case 10:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10" selected>Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';
		break;
	case 11:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11" selected>Noviembre</option>'; 
		echo '<option value="12">Diciembre</option>'; 
		echo '</select>';
		break;
	case 12:
		echo '<select name="combo">';
		echo '<option value="1">Enero</option>';
		echo '<option value="2">Febrero</option>';
		echo '<option value="3">Marzo</option>';
		echo '<option value="4">Abril</option>'; 
		echo '<option value="5">Mayo</option>'; 
		echo '<option value="6">Junio</option>'; 
		echo '<option value="7">Julio</option>'; 
		echo '<option value="8">Agosto</option>';
		echo '<option value="9">Septiembre</option>'; 
		echo '<option value="10">Octubre</option>'; 
		echo '<option value="11">Noviembre</option>'; 
		echo '<option value="12" selected>Diciembre</option>'; 
		echo '</select>';
		break;	
	default:
		echo "No valido";
		break;
}
?>